{{- $namespace := .Values.namespace }}
{{- $chartname := .Chart.Name }}
{{- $chartversion := .Chart.Version }}

{{- range $service := .Values.stateless }}
{{- if $service.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $service.name }}-sa-ksa
  namespace: {{ $namespace }}
  labels:
    chart: "{{ $chartname }}-{{ $chartversion | replace "+" "_" }}"
{{- if $service.serviceAccount.annotations }}
  annotations:
{{- range $key, $value := $service.serviceAccount.annotations }}
    {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
---
{{- end }}
{{- end }}
